version: '3.8'

services: 
    jupyter_container:
        build:
            context: .
        init: true
        ports:
            - 8888:8888
        environment:
            - JUPYTER_ALLOW_INSECURE_WRITES=true
        volumes:
            - ./Python:/home/jovyan/work
