version: '3.8'

services: 
    jupyter_container:
        build:
            context: .
        init: true
        ports:
            - 8888:8888
        volumes:
            - ./Python:/home/jovyan/
